name: budget
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyside6
  - matplotlib
  - python-dateutil
  - pyinstaller
  - pip
  - pip:
    - qt-material  # optional: modern Material Design theme for PySide6
